blueprint:
  name: Thermostat Night Mode
  description: Set BT Thermostats to night mode if Schedule event is active.
  domain: automation
  source_url: https://github.com/Master2386/homeassistant/blob/main/blueprints/Thermostat_Night_Mode.yml
  input:
    night_times_schedule:
      name: Schedule helper
      selector:
        entity:
          domain: schedule

    thermostat_target:
      name: Thermostats
      selector:
        target:
          device:
            integration: better_thermostat
          entity:
            integration: better_thermostat
            domain: climate

    day_temp:
      name: Day Temperature
      selector:
        target:
          entity:
            domain: input_number

    night_temp:
      name: Night Temperature
      selector:
        target:
          entity:
            domain: input_number

mode: queued
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input night_times_schedule
    from: "on"
    to: "off"
  - platform: state
    entity_id: !input night_times_schedule
    from: "off"
    to: "on"
condition: []
action:
  - if:
      - condition: state
        entity_id: !input night_times_schedule
        state: "on"
    then:
      - service: better_thermostat.set_temp_target_temperature
        data:
          temperature: "{{ states(!input night_temp) | float }}"
        target: !input thermostat_target
    else:
      - service: better_thermostat.set_temp_target_temperature
        data:
          temperature: "{{ states(!input day_temp) | float }}"
        target: !input thermostat_target
