blueprint:
  name: Thermostat Night Mode
  description: Set Better Thermostats to night/day temperature based on a schedule.
  domain: automation

  input:
    night_times_schedule:
      name: Schedule helper
      selector:
        entity:
          domain: schedule

    thermostat_target:
      name: Thermostats
      selector:
        target:
          device:
            integration: better_thermostat
          entity:
            domain: climate
            integration: better_thermostat

    night_temp:
      name: Night Temperature
      selector:
        entity:
          domain: input_number

    day_temp:
      name: Day Temperature
      selector:
        entity:
          domain: input_number

mode: queued
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input night_times_schedule
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input night_times_schedule
    from: "on"
    to: "off"

condition: []

action:
  - if:
      - condition: state
        entity_id: !input night_times_schedule
        state: "on"
    then:
      - service: better_thermostat.set_temp_target_temperature
        target: !input thermostat_target
        data:
          temperature: "{{ states(( !input night_temp )) | float }}"
    else:
      - service: better_thermostat.set_temp_target_temperature
        target: !input thermostat_target
        data:
          temperature: "{{ states(( !input day_temp )) | float }}"